---
name: SNMP-Agent
version: 0.01
author:
  - 'Alexander Else <aelse@else.id.au>'
abstract: A simple SNMP AgentX subagent
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  NetSNMP::ASN: 0
  NetSNMP::agent: 0
  Test::More: 0
configure_requires:
  Module::Build: 0.340201
provides:
  SNMP::Agent:
    file: lib/SNMP/Agent.pm
    version: 0.01
generated_by: Module::Build version 0.340201
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
